LOCAL_CPPFLAGS:=$(CPPFLAGS)
LOCAL_CFLAGS:=$(CFLAGS)
LOCAL_CXXFLAGS:=$(CXXFLAGS)
LOCAL_LDFLAGS:=$(LDFLAGS)
LOCAL_LIBADD:=$(LIBADD)

LOCAL_CPPFLAGS+=-I${R} -I. -I${R}/include -I${R}/common
LOCAL_CFLAGS+=
LOCAL_LDFLAGS+=$(LOCAL_CFLAGS)
